"""Added fname sname atributes to user table and fixed_town to order table

Revision ID: 007cee9b9ccf
Revises: b1ea524cf224
Create Date: 2026-02-02 16:36:19.870709

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '007cee9b9ccf'
down_revision = 'b1ea524cf224'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fixed_town', sa.String(length=30), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fname', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('sname', sa.String(length=30), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('sname')
        batch_op.drop_column('fname')

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('fixed_town')

    # ### end Alembic commands ###
