"""Added order table to db

Revision ID: 13ac56bf79cb
Revises: def6bed358c3
Create Date: 2026-02-01 16:34:21.904036

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13ac56bf79cb'
down_revision = 'def6bed358c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fname', sa.String(length=20), nullable=False),
    sa.Column('sname', sa.String(length=30), nullable=False),
    sa.Column('quantity', sa.Integer(), server_default='1', nullable=False),
    sa.Column('town', sa.String(length=30), nullable=False),
    sa.Column('mail', sa.String(length=10), nullable=False),
    sa.Column('index', sa.Integer(), nullable=False),
    sa.Column('comm', sa.Text(), nullable=True),
    sa.Column('seller_id', sa.Integer(), nullable=False),
    sa.Column('buyer_id', sa.Integer(), nullable=False),
    sa.Column('good_id', sa.Integer(), nullable=True),
    sa.Column('fixed_title', sa.String(length=150), nullable=False),
    sa.Column('fixed_price', sa.Integer(), nullable=False),
    sa.Column('fixed_img_url', sa.String(length=200), nullable=False),
    sa.Column('fixed_slug', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['buyer_id'], ['user.id'], name=op.f('fk_orders_buyer_id_user')),
    sa.ForeignKeyConstraint(['good_id'], ['good.id'], name=op.f('fk_orders_good_id_good'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['seller_id'], ['user.id'], name=op.f('fk_orders_seller_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_orders'))
    )
    with op.batch_alter_table('good', schema=None) as batch_op:
        batch_op.add_column(sa.Column('orders', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('good', schema=None) as batch_op:
        batch_op.drop_column('orders')

    op.drop_table('orders')
    # ### end Alembic commands ###
