"""Changed nullable to False in orders,fname and sname atributes

Revision ID: 23904ff50c41
Revises: 0a8f3f957c96
Create Date: 2026-02-06 17:22:56.868354

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23904ff50c41'
down_revision = '0a8f3f957c96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('good', schema=None) as batch_op:
        batch_op.alter_column('orders',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('fname',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('sname',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('sname',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
        batch_op.alter_column('fname',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)

    with op.batch_alter_table('good', schema=None) as batch_op:
        batch_op.alter_column('orders',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
