"""Added new table tg users

Revision ID: 31813025cde9
Revises: 68865c711616
Create Date: 2026-02-24 18:18:30.083406

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31813025cde9'
down_revision = '68865c711616'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bot_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_telegram_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bot_user')),
    sa.UniqueConstraint('user_telegram_id', name=op.f('uq_bot_user_user_telegram_id'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bot_user')
    # ### end Alembic commands ###
