"""Added state atribute to order table and town atribute to good table

Revision ID: 3b074d8fe1a6
Revises: 635dce97fad9
Create Date: 2026-02-01 22:54:12.910777

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b074d8fe1a6'
down_revision = '635dce97fad9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('good', schema=None) as batch_op:
        batch_op.add_column(sa.Column('town', sa.String(length=30), nullable=True))

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('state', sa.String(length=10), server_default='Очікує підтвердження', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('state')

    with op.batch_alter_table('good', schema=None) as batch_op:
        batch_op.drop_column('town')

    # ### end Alembic commands ###
