"""Added bot login table

Revision ID: 57e885367bec
Revises: 31813025cde9
Create Date: 2026-02-25 18:51:13.133427

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57e885367bec'
down_revision = '31813025cde9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bot_login',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_telegram_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_bot_login_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bot_login')),
    sa.UniqueConstraint('user_telegram_id', name=op.f('uq_bot_login_user_telegram_id'))
    )
    op.drop_table('_alembic_tmp_bot_user')
    with op.batch_alter_table('bot_user', schema=None) as batch_op:
        batch_op.alter_column('user_telegram_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bot_user', schema=None) as batch_op:
        batch_op.alter_column('user_telegram_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)

    op.create_table('_alembic_tmp_bot_user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_telegram_id', sa.BIGINT(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_bot_user_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bot_user')),
    sa.UniqueConstraint('user_telegram_id', name=op.f('uq_bot_user_user_telegram_id'))
    )
    op.drop_table('bot_login')
    # ### end Alembic commands ###
