"""Rename of index colum to zip_code

Revision ID: 635dce97fad9
Revises: 13ac56bf79cb
Create Date: 2026-02-01 16:56:38.843260

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '635dce97fad9'
down_revision = '13ac56bf79cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('zip_code', sa.Integer(), nullable=False))
        batch_op.drop_column('index')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('index', sa.INTEGER(), nullable=False))
        batch_op.drop_column('zip_code')

    # ### end Alembic commands ###
