"""First migration

Revision ID: 67de6bb61fa7
Revises: 
Create Date: 2026-04-23 12:13:53.377590

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67de6bb61fa7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bot_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_telegram_id', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bot_user')),
    sa.UniqueConstraint('user_telegram_id', name=op.f('uq_bot_user_user_telegram_id'))
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=1000), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('fname', sa.String(length=20), nullable=False),
    sa.Column('sname', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user')),
    sa.UniqueConstraint('email', name=op.f('uq_user_email')),
    sa.UniqueConstraint('slug', name=op.f('uq_user_slug')),
    sa.UniqueConstraint('username', name=op.f('uq_user_username'))
    )
    op.create_table('bot_login',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_telegram_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_bot_login_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bot_login')),
    sa.UniqueConstraint('user_telegram_id', name=op.f('uq_bot_login_user_telegram_id'))
    )
    op.create_table('good',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('descr', sa.Text(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('user_slug', sa.String(length=255), nullable=True),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('quantity', sa.Integer(), server_default='1', nullable=False),
    sa.Column('orders', sa.Integer(), server_default='1', nullable=False),
    sa.Column('town', sa.String(length=30), nullable=False),
    sa.Column('lower_title', sa.String(length=100), nullable=False),
    sa.CheckConstraint('price >= 0', name=op.f('ck_good_price_positive')),
    sa.ForeignKeyConstraint(['user_slug'], ['user.slug'], name=op.f('fk_good_user_slug_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_good')),
    sa.UniqueConstraint('slug', name=op.f('uq_good_slug'))
    )
    op.create_table('order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fname', sa.String(length=20), nullable=False),
    sa.Column('sname', sa.String(length=30), nullable=False),
    sa.Column('quantity', sa.Integer(), server_default='1', nullable=False),
    sa.Column('town', sa.String(length=30), nullable=False),
    sa.Column('mail', sa.String(length=10), nullable=False),
    sa.Column('zip_code', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=10), server_default='waiting', nullable=False),
    sa.Column('comm', sa.Text(), nullable=True),
    sa.Column('seller_id', sa.Integer(), nullable=False),
    sa.Column('buyer_id', sa.Integer(), nullable=False),
    sa.Column('good_id', sa.Integer(), nullable=True),
    sa.Column('fixed_title', sa.String(length=150), nullable=False),
    sa.Column('fixed_price', sa.Integer(), nullable=False),
    sa.Column('fixed_img_url', sa.String(length=200), nullable=False),
    sa.Column('fixed_slug', sa.String(length=255), nullable=False),
    sa.Column('fixed_town', sa.String(length=30), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['buyer_id'], ['user.id'], name=op.f('fk_order_buyer_id_user')),
    sa.ForeignKeyConstraint(['good_id'], ['good.id'], name=op.f('fk_order_good_id_good'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['seller_id'], ['user.id'], name=op.f('fk_order_seller_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_order'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order')
    op.drop_table('good')
    op.drop_table('bot_login')
    op.drop_table('user')
    op.drop_table('bot_user')
    # ### end Alembic commands ###
