"""Added lower_title column to good table

Revision ID: 67f703535778
Revises: 23904ff50c41
Create Date: 2026-02-07 23:00:27.636542

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67f703535778'
down_revision = '23904ff50c41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('good', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lower_title', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('good', schema=None) as batch_op:
        batch_op.drop_column('lower_title')

    # ### end Alembic commands ###
