"""nothing changed

Revision ID: 68865c711616
Revises: 67f703535778
Create Date: 2026-02-18 21:46:51.572680

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68865c711616'
down_revision = '67f703535778'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('good', schema=None) as batch_op:
        batch_op.alter_column('lower_title',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('good', schema=None) as batch_op:
        batch_op.alter_column('lower_title',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    # ### end Alembic commands ###
