"""Added column quantity

Revision ID: def6bed358c3
Revises: 
Create Date: 2026-01-26 17:49:18.034486

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'def6bed358c3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('good', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantity', sa.Integer(), server_default='1', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('good', schema=None) as batch_op:
        batch_op.drop_column('quantity')

    # ### end Alembic commands ###
