"""Rename of oreders table to order

Revision ID: e524adc4acac
Revises: 3b074d8fe1a6
Create Date: 2026-02-01 22:58:04.858791

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e524adc4acac'
down_revision = '3b074d8fe1a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('orders','order')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('orders', 'order')

    # ### end Alembic commands ###
